name: Pull Request Branch Test
run-name: Running smoke tests against the branch that creates a pull request

on:
  pull_request:
    branches:
      - main
jobs:
  pr-branch-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Run Smoke Tests against the PR branch
        run: mvn test -Dcucumber.filter.tags="@smoke" -Dbrowser=chromeheadless

      - name: Attach Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Result Report File
          path: target/cucumber-report/report.html
