name: Regression test Suite
run-name: Running regression tests
on:
  schedule:
#    - cron: '0 0 * * *'  runs every midnight, typical frequency for regression tests
    - cron: '*/15 * * * *'  # every 15 mins, minimum amount of frequency is 15 mins in GitHub Actions
#    - cron: '10,15 * * * *'  # every 10th and 30th minute
#    - cron: '0 0 1,15 * *'  # every 1st and 15th day of the month ar midnight
#    - cron: '0 0 * * 6,0'  # every Saturday and Sunday at midnight
#    - cron: '0 0 * * 1-5'  # Monday to Friday at midnight

 # any workflow can combine multiple types of triggers like push, PR or on schedule
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Run Regression Tests
        run: mvn test -Dbrowser=chromeheadless

      - name: Attach Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Result Report File
          path: target/cucumber-report/report.html


