name: Smoke tests UI and DB
#run name shows up in GitHub actions for each run, by default it is the commit message
run-name: Running smoke tests UI and DB in parallel
on:
  push:
    branches:
      - main
jobs:
  smoke-test-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Run Smoke Tests
        run: mvn test -Dcucumber.filter.tags="@smoke" -Dbrowser=chromeheadless

  smoke-test-db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      - name: Run DB Smoke Tests
        run: mvn test -Dcucumber.filter.tags="@DB" -Dbrowser=chromeheadless